#!/usr/bin/env bash

if
  [[ -s "/home/ubuntu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/environment" ]]
then
  source "/home/ubuntu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/environment"
  exec irb "$@"
else
  echo "ERROR: Missing RVM environment file: '/home/ubuntu/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/environment'" >&2
  exit 1
fi
